### ISSUE TITLE
Groq 코드 리뷰를 위한 기능 구성

### ISSUE THREAD

**Issue by YeaChan05** [minturtle/CareerSupport#34]
## 어떤 기능인가요?

> 
### 요구사항

- 사용자가 github pull request를 보낼때 Spring AI를 사용한 Groq의 코드 리뷰를 통해 사용자의 코드 개선 가능성 제공

### 해결방안

- 사용자가 pr을 올리거나 pr에 push를 할 때마다  Spring AI가 리뷰를 달도록(비동기) 요청
- 이때 사용하는 Github API들에 공통적으로 필요한 파라미터를 모아 하나의 엔드포인트에서 처리 가능하도록 구현

### 진행 방식
1. [pr에 올라온 파일들을 전부 조회](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests-files): AI에게 리뷰를 받기 위해 pr 변경 파일들을 전부 조회
2. 해당 파일 정보를 Spring AI를 통해 리뷰사항 생성
3. [리뷰 정보를 comment로 남김](https://docs.github.com/en/rest/pulls/comments?apiVersion=2022-11-28#create-a-review-comment-for-a-pull-request): AI가 작성한 리뷰내용을 comment로 작성

### 예시

```yaml
- name: Review This Pull Request
        run: |
          curl -X POST "https://careersupport.serveblog.net/review" \
          -H "Content-Type: application/json" \
          -H "Authenticate: ${{ secrets.REVIEW_TOKEN }}" \
          -d '{
            "token": "${{ secrets.GITHUB_TOKEN }}",
            "repository": "${{ github.repository }}", #{owner-name}/{repo-name}을 제공, API 요청시 사용됨
            "pr_number": "${{ github.event.pull_request.number || github.event.number }}", # pr 번호 확인
          }'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## 작업 상세 내용

- [ ] PR에 변경된 파일 조회
- [ ] 변경된 파일을 리뷰 가능한 형태로 작성하도록 Spring AI 설정
- [ ] 작성된 리뷰를 comment 형태로 요청

## 참고할만한 자료(선택)
https://docs.github.com/en/rest/about-the-rest-api/about-the-rest-api?apiVersion=2022-11-28
